src/Entity/Media.php
<?php

namespace App\Entity;

use App\Repository\MediaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MediaRepository::class)
 */
class Media
{

    const ARTICLE = "article";
    const AUDIO = "audio";
    const VIDEO = "video";


    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

//    private $media = array(
//        'article' => 'article',
//        'audio' => 'audio',
//        'video' => 'video'
//        );

    /**
     * @var string|null
     * @ORM\Column
     */
    private $titre;



    /**
     * @var string|null
     * @ORM\Column
     */
    private ?string $typeMedia;


    /**
     * @var \DateTimeImmutable
     * @ORM\Column(type="datetime_immutable")
     */
    private \DateTimeImmutable $date_publication;

    /**
     * @var string
     * @ORM\Column
     */
    private $url;


    /**
     * @var string
     * @ORM\Column
     */
    private $nom_auteur;




    /**
     * @var string
     * @ORM\Column
     */
    private $urlImage;

    /**
     * @var string|null
     * @ORM\Column(type="text")
     */
    private ?string $resume;

    /**
     * @var Collection
     * @ORM\OneToMany(targetEntity="App\Entity\Commentaire", mappedBy="media")
     */
    private $commentaire;

    /**
     * @ORM\OneToMany(targetEntity=LikeMedia::class, mappedBy="media")
     */
    private $likeMedia;

    /**
     * Media constructor.
     * @throws \Exception
     */
    public function __construct()
    {
        $this->date_publication = new \DateTimeImmutable();
        $this->commentaire = new ArrayCollection();
        $this->likeMedia = new ArrayCollection();
    }

    /**
     * @return string|null
     */
    public function getTypeMedia(): ?string
    {
        return $this->typeMedia;
    }

    /**
     * @param string|null $typeMedia
     */
    public function setTypeMedia(?string $typeMedia): void
    {
        $this->typeMedia = $typeMedia;
    }

    /**
     * @return string|null
     */
    public function getResume(): ?string
    {
        return $this->resume;
    }

    /**
     * @param string|null $resume
     */
    public function setResume(?string $resume): void
    {
        $this->resume = $resume;
    }






    /**
     * @return \DateTimeImmutable
     */
    public function getDatePublication(): \DateTimeImmutable
    {
        return $this->date_publication;
    }

    /**
     * @param \DateTimeImmutable $date_publication
     */
    public function setDatePublication(\DateTimeImmutable $date_publication): void
    {
        $this->date_publication = $date_publication;
    }

    /**
     * @return string
     */
    public function getUrl(): string
    {
        return $this->url;
    }

    /**
     * @param string $url
     */
    public function setUrl(string $url): void
    {
        $this->url = $url;
    }

    /**
     * @return string
     */
    public function getUrlImage(): string
    {
        return $this->urlImage;
    }

    /**
     * @param string $urlImage
     */
    public function setUrlImage(string $urlImage): void
    {
        $this->urlImage = $urlImage;
    }






    public function getId(): ?int
    {
        return $this->id;
    }


    /**
     * @return string
     */
    public function getNomAuteur(): string
    {
        return $this->nom_auteur;
    }

    /**
     * @param string $nom_auteur
     */
    public function setNomAuteur(string $nom_auteur): void
    {
        $this->nom_auteur = $nom_auteur;
    }

    /**
     * @return string
     */
    public function getTitre(): string
    {
        return $this->titre;
    }

    /**
     * @param string $titre
     */
    public function setTitre(string $titre): void
    {
        $this->titre = $titre;
    }

    /**
     * @return Collection
     */
    public function getCommentaire(): ?Collection
    {
        return $this->commentaire;
    }

    /**
     * @param Collection $commentaire
     */
    public function setCommentaire(Collection $commentaire): void
    {
        $this->commentaire = $commentaire;
    }

    /**
     * @return Collection|LikeMedia[]
     */
    public function getLikeMedia(): Collection
    {
        return $this->likeMedia;
    }

    public function addLikeMedium(LikeMedia $likeMedium): self
    {
        if (!$this->likeMedia->contains($likeMedium)) {
            $this->likeMedia[] = $likeMedium;
            $likeMedium->setMedia($this);
        }

        return $this;
    }

    public function removeLikeMedium(LikeMedia $likeMedium): self
    {
        if ($this->likeMedia->contains($likeMedium)) {
            $this->likeMedia->removeElement($likeMedium);
            // set the owning side to null (unless already changed)
            if ($likeMedium->getMedia() === $this) {
                $likeMedium->setMedia(null);
            }
        }

        return $this;
    }


    /**
     * permet de savoir si ce media est liké par un utilisateur
     * @param User $user
     * @return bool
     */
    public function isLikedByUser(User $user) : bool
    {
        foreach ($this->likeMedia as $like) {
            if ($like->getUser() === $user) return  true;
        }

        return false;
    }


}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}
        <link rel="stylesheet" href="{{ asset('css/plugins.css') }}">
        <link rel="stylesheet" href="{{ asset('css/style.css') }}">{% endblock %}

       <style>
          .page-header {
             background: url({{ asset('images/blog1.jpg') }}) no-repeat;
          }

       </style>
    </head>
    <body>
        {% block body %}
           <!--PreLoader-->
           <div class="loader">
              <div class="loader-inner">
                 <div class="loader-blocks">
                    <span class="block-1"></span>
                    <span class="block-2"></span>
                    <span class="block-3"></span>
                    <span class="block-4"></span>
                    <span class="block-5"></span>
                    <span class="block-6"></span>
                    <span class="block-7"></span>
                    <span class="block-8"></span>
                    <span class="block-9"></span>
                    <span class="block-10"></span>
                    <span class="block-11"></span>
                    <span class="block-12"></span>
                    <span class="block-13"></span>
                    <span class="block-14"></span>
                    <span class="block-15"></span>
                    <span class="block-16"></span>
                 </div>
              </div>
           </div>
           <!--PreLoader Ends-->


           <!-- header -->
           <header class="site-header">
              <nav class="navbar navbar-expand-lg transparent-bg static-nav">
                 <div class="container">
                    <a class="navbar-brand" href="index.html">
                       <img src="{{ asset('images/logo-transparent.png') }}" alt="logo">
                    </a>
                    <button class="navbar-toggler navbar-toggler-right collapsed" type="button" data-toggle="collapse" data-target="#xenav">
                       <span> </span>
                       <span> </span>
                       <span> </span>
                    </button>
                    <div class="collapse navbar-collapse" id="xenav">
                       <ul class="navbar-nav ml-auto">
                          <li class="nav-item active">
                             <a class="nav-link" href="index.html#banner-main" data-text="Home">Home</a>
                          </li>
                          <li class="nav-item">
                             <a class="nav-link" href="index.html#our-process" data-text="Features">Features</a>
                          </li>
                          <li class="nav-item">
                             <a class="nav-link" href="index.html#our-team" data-text="Team">Team</a>
                          </li>
                          <li class="nav-item">
                             <a class="nav-link" href="index.html#portfolio_top" data-text="Portfolio">Portfolio</a>
                          </li>
                          <li class="nav-item">
                             <a class="nav-link" href="index.html#our-pricings" data-text="Packages">Packages</a>
                          </li>
                          <li class="nav-item">
                             <a class="nav-link" href="index.html#our-testimonial" data-text="Clients">Clients</a>
                          </li>
                          <li class="nav-item">
                             <a class="nav-link" href="index.html#our-blog" data-text="Blog">Blog</a>
                          </li>
                          <li class="nav-item">
                             <a class="nav-link" href="index.html#contactus" data-text="contact">contact</a>
                          </li>
                           {% if app.user %}
                               <li class="nav-item">
                                   <span class="badge-success nav-link ">{{ app.user.nom }}</span>
                               </li>

                           {% else %}
                           <li class="nav-item">
                               <a class="nav-link text-primary" href="{{ path('app_login') }}"  >Connexion</a>
                           </li>
                           {% endif %}
                       </ul>
                    </div>
                 </div>



                 <!--side menu open button-->
                 <a href="javascript:void(0)" class="d-none d-lg-inline-block sidemenu_btn" id="sidemenu_toggle">
                    <span></span> <span></span> <span></span>
                 </a>
              </nav>

              <!-- side menu -->
              <div class="side-menu">
                 <div class="inner-wrapper">
                    <span class="btn-close" id="btn_sideNavClose"><i></i><i></i></span>
                    <nav class="side-nav">
                       <ul class="navbar-nav w-100">
                          <li class="nav-item active">
                             <a class="nav-link" href="index.html#banner-main">Home</a>
                          </li>
                          <li class="nav-item">
                             <a class="nav-link" href="index.html#our-process">Features</a>
                          </li>
                          <li class="nav-item">
                             <a class="nav-link" href="index.html#our-team">Team</a>
                          </li>
                          <li class="nav-item">
                             <a class="nav-link" href="index.html#portfolio_top">Portfolio</a>
                          </li>
                          <li class="nav-item">
                             <a class="nav-link" href="index.html#our-pricings">Packages</a>
                          </li>
                          <li class="nav-item">
                             <a class="nav-link" href="#our-testimonial">Clients</a>
                          </li>
                          <li class="nav-item">
                             <a class="nav-link" href="index.html#our-blog">Blog</a>
                          </li>
                          <li class="nav-item">
                             <a class="nav-link" href="index.html#contactus">contact</a>
                          </li>
                       </ul>
                    </nav>

                    <div class="side-footer w-100">
                       <ul class="social-icons-simple white top40">
                          <li><a href="javascript:void(0)"><i class="fa fa-facebook"></i> </a> </li>
                          <li><a href="javascript:void(0)"><i class="fa fa-instagram"></i> </a> </li>
                          <li><a href="javascript:void(0)"><i class="fa fa-twitter"></i> </a> </li>
                       </ul>
                       <p class="whitecolor">&copy; 2018 XeOne. Made With Love by themesindustry</p>
                    </div>
                 </div>
              </div>
              <a id="close_side_menu" href="javascript:void(0);"></a>
              <!-- End side menu -->
           </header>
           <!-- header -->





                   {% block main_content %} {% endblock %}





           <!--Site Footer Here-->
           <footer id="site-footer" class="padding_half">
              <div class="container">
                 <div class="row">
                    <div class="col-md-12 col-sm-12 text-center">
                       <ul class="social-icons bottom25">
                          <li><a href="javascript:void(0)"><i class="fa fa-facebook"></i> </a> </li>
                          <li><a href="javascript:void(0)"><i class="fa fa-twitter"></i> </a> </li>
                          <li><a href="javascript:void(0)"><i class="fa fa-google-plus"></i> </a> </li>
                          <li><a href="javascript:void(0)"><i class="fa fa-linkedin"></i> </a> </li>
                          <li><a href="javascript:void(0)"><i class="fa fa-instagram"></i> </a> </li>
                          <li><a href="javascript:void(0)"><i class="fa fa-envelope-o"></i> </a> </li>
                       </ul>
                       <p class="copyrights"> &copy; 2019 XeOne. made with love by <a href="http://www.themesindustry.com/" target="_blank">themesindustry</a> </p>
                    </div>
                 </div>
              </div>
           </footer>
           <!--Footer ends-->
           <!--Footer ends-->
           <!--Footer ends-->
        {% endblock %}
        {% block javascripts %}
        <script src="{{ asset('js/jquery-3.1.1.min.js') }}"></script>
        <script src="{{ asset('js/popper.min.js') }}"></script>
        <script src="{{ asset('js/bootstrap.min.js') }}"></script>
        <script src="{{ asset('js/jquery.appear.js') }}"></script>
        <script src="{{ asset('js/jquery.matchHeight-min.js') }}"></script>
        <script src="{{ asset('js/owl.carousel.min.js') }}"></script>
        <script src="{{ asset('js/jquery-countTo.js') }}"></script>
        <script src="{{ asset('js/parallaxie.js') }}"></script>
        <script src="{{ asset('js/jquery.cubeportfolio.min.js') }}"></script>
        <script src="{{ asset('js/jquery.fancybox.min.js') }}"></script>
        <script src="{{ asset('js/jquery.background-video.js') }}"></script>
        <script src="{{ asset('js/typewriter.js') }}"></script>
        <script src="{{ asset('js/particles.min.js') }}"></script>
        <script src="{{ asset('js/wow.min.js') }}"></script>
        <script src="{{ asset('js/revolution/jquery.themepunch.tools.min.js') }}"></script>
        <script src="{{ asset('js/revolution/jquery.themepunch.revolution.min.js') }}"></script>
        <script src="{{ asset('js/revolution/extensions/revolution.extension.actions.min.js') }}"></script>
        <script src="{{ asset('js/revolution/extensions/revolution.extension.carousel.min.js') }}"></script>
        <script src="{{ asset('js/revolution/extensions/revolution.extension.kenburn.min.js') }}"></script>
        <script src="{{ asset('js/revolution/extensions/revolution.extension.layeranimation.min.js') }}"></script>
        <script src="{{ asset('js/revolution/extensions/revolution.extension.migration.min.js') }}"></script>
        <script src="{{ asset('js/revolution/extensions/revolution.extension.navigation.min.js') }}"></script>
        <script src="{{ asset('js/revolution/extensions/revolution.extension.parallax.min.js') }}"></script>
        <script src="{{ asset('js/revolution/extensions/revolution.extension.slideanims.min.js') }}"></script>
        <script src="{{ asset('js/revolution/extensions/revolution.extension.video.min.js') }}"></script>
        <script src="{{ asset('js/functions.js') }}"></script>
            <script src="https://unpkg.com/axios/dist/axios.min.js"></script>



<!--Bootstrap Core-->
{#<script src="./js/popper.min.js"></script>#}
{#<script src="./js/bootstrap.min.js"></script>#}

{#<!--to view items on reach-->#}
{#<script src="./js/jquery.appear.js"></script>#}

{#<!--Equal-Heights-->#}
{#<script src="./js/jquery.matchHeight-min.js"></script>#}

{#<!--Owl Slider-->#}
{#<script src="./js/owl.carousel.min.js"></script>#}

{#<!--number counters-->#}
{#<script src="./js/jquery-countTo.js"></script>#}
{# #}
{#<!--Parallax Background-->#}
{#<script src="./js/parallaxie.js"></script>#}
{#  #}
{#<!--Cubefolio Gallery-->#}
{#<script src="./js/jquery.cubeportfolio.min.js"></script>#}

{#<!--FancyBox popup-->#}
{#<script src="./js/jquery.fancybox.min.js"></script>#}
{#      #}
{#<!-- Video Background-->#}
{#<script src="./js/jquery.background-video.js"></script>#}

{#<!--TypeWriter-->#}
{#<script src="./js/typewriter.js"></script>#}
{#      #}
{#<!--Particles-->#}
{#<script src="./js/particles.min.js"></script>#}
{#  #}
{#<!--WOw animations-->#}
{#<script src="./js/wow.min.js"></script>#}
{#   #}
{#<!--Revolution SLider-->#}
{#<script src="./js/revolution/jquery.themepunch.tools.min.js"></script>#}
{#<script src="./js/revolution/jquery.themepunch.revolution.min.js"></script>#}
{#<!-- SLIDER REVOLUTION 5.0 EXTENSIONS  (Load Extensions only on Local File Systems !  The following part can be removed on Server for On Demand Loading) -->#}
{#<script src="./js/revolution/extensions/revolution.extension.actions.min.js"></script>#}
{#<script src="./js/revolution/extensions/revolution.extension.carousel.min.js"></script>#}
{#<script src="./js/revolution/extensions/revolution.extension.kenburn.min.js"></script>#}
{#<script src="./js/revolution/extensions/revolution.extension.layeranimation.min.js"></script>#}
{#<script src="./js/revolution/extensions/revolution.extension.migration.min.js"></script>#}
{#<script src="./js/revolution/extensions/revolution.extension.navigation.min.js"></script>#}
{#<script src="./js/revolution/extensions/revolution.extension.parallax.min.js"></script>#}
{#<script src="./js/revolution/extensions/revolution.extension.slideanims.min.js"></script>#}
{#<script src="./js/revolution/extensions/revolution.extension.video.min.js"></script>#}
{#  #}
{#<script src="./js/functions.js"></script>#}

        {% endblock %}
    </body>
</html>

templates/blog.html.twig
{% extends "base.html.twig" %}




{% block main_content %}

    <!--page Header-->
    <section class="page-header parallaxie padding_top center-block">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-titles text-center" style="text-transform: none; min-height:200Px;">
                        <h2 class="whitecolor font-light bottom30"  ></h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--page Header ends-->

    <!-- Our Blogs -->
    <section id="our-blog" class="bglight padding text-center">
        <div class="container">
            <div id="blog-measonry" class="cbp">
                {% for key, media in medias %}
                    <div class="cbp-item">
                        <div class="news_item shadow">
                            <a class="image" href="{{ path('afficheMedia', {'urlMedia':media.url}) }}">

                                    {% set path='images/'~media.urlImage %}
                                    <img src="{{ asset(path) }}" alt="" class="img-responsive" >

                            </a>
                            <div class="news_desc">
                                <h3 class="font-light darkcolor">
                                    <a class="image" href="{{ path('afficheMedia', {'urlMedia':media.url}) }}">
                                        {{media.titre}}
                                    </a>
                                </h3>
                                <ul class="meta-tags top20 bottom20">
                                    <li><i class="fa fa-calendar"></i> {{media.datePublication|date('d/m/y')}}</li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-user"></i> {{media.nomAuteur}}
                                        </a>
                                    </li>
                                </ul>
                                <p class="bottom35">{{media.resume|nl2br}}</p>
                                <a class="image button btnprimary btn-gradient-hvr" href="{{ path('afficheMedia', {'urlMedia':media.url}) }}">
                                    Lire la suite
                                </a>
                            </div>
                        </div>
                    </div>

                {% endfor %}
            </div>
        </div>
    </section>
    <!--Our Blogs Ends-->

{% endblock %}

templates/comment.html.twig
{%  extends "base.html.twig" %}


{% form_theme form _self %}

{#{% block form_start %}#}
{#	<form class="getin_form" id="post-a-comment"></form>#}
{#{% endblock %}#}

{% block textarea_widget %}

    <textarea class="form-control" {{ block('widget_attributes') }} placeholder="Entrer le contenu de votre commentaire" required>{{ value }}</textarea>
{% endblock  %}

{% block text_widget  %}
    <input class="form-control" {{ block('widget_attributes') }} placeholder="Nom" required value="{{ value }}">
{% endblock  %}


{% block main_content %}

    <section class="page-header parallaxie padding_top center-block">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-titles text-center" style="text-transform: none; min-height:200Px;">
                        <h2 class="whitecolor font-light bottom30"  ></h2>
                    </div>
                </div>
            </div>
        </div>
    </section><br><br><br>


<section id="our-blog" class="padding bglight">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="news_item shadow">
                <div class="news_desc text-left">
<div class="post-comment">
    {{ form_start(form) }}
    <div class="row">
        <div class="col-md-6 col-sm-6">
            <div class="form-group bottom35">
                {{ form_row(form.auteur) }}
            </div>
        </div>
            <div class="col-md-12 col-sm-12">
                <div class="form-group bottom35">
                    {{ form_row(form.contenu) }}
                </div>
                <div class="col-sm-12">
                    <button type="submit" class="button btnprimary">Envoyer</button>
                </div>
            </div>
            {{ form_end(form) }}

    </div>
</div>

    {% if comments %}
        <br><br><br>
        <div class="profile-authors heading_space">
            <h4 class="text-capitalize darkcolor bottom40">Commentaires</h4>
            {% for comment in comments %}

                <div class="eny_profile bottom30">
                    {#						   <div class="profile_photo"><img src="{{asset('images/franck.jpg')}}" alt="Comments"> </div>#}
                    <div class="profile_text">
                        <h6 class="darkcolor"><a href="#.">{{comment.auteur}}</a></h6>
                        <p class="top10">{{comment.contenu}}</p>
                        <a class="text-primary h4" href="#." title="liker"><i class="fa fa-thumbs-up "></i></a>&nbsp;&nbsp;
                        <a class="text-danger h4" href="#." title="disliker"><i class="fa fa-thumbs-down "></i></a>
                        {#							   <a  href="{{ path('afficheComments', {'comParent':comment}) }}">#}
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                        <a class="font-light darkcolor" href="{{ path('afficheComments', {'idParent':comment.id}) }}">

                            Répondre
                        </a>&nbsp;&nbsp;&nbsp;&nbsp;

                        <a class=" font-light darkcolor" href="{{path('afficheComments', {'idParent':comment.id}) }}">
                            Commentaires({{comment.children| length}})
                        </a>
                    </div>
                </div>
                {#					   <div class="eny_profile">#}
                {#						   <div class="profile_photo"><img src="images/testimonial-2.jpg" alt="Comments"> </div>#}
                {#						   <div class="profile_text">#}
                {#							   <h6 class="darkcolor"><a href="#.">Jkristen Smith</a></h6>#}
                {#							   <p class="top10">Keeping your eye on the ball while performing. Podcasting operational change management inside of workflows to establish a framework. </p>#}
                {#						   </div>#}
                {#					   </div>#}

            {% endfor %}
        </div>

    {% endif %}
                </div>
                </div>
            </div>
            </div>
        </div>

</section>
{% endblock %}